ALL = PrototypeBigSimulation3 ProtoBigSimNoBrunet SimWithCorrelatedDataNoBrunet1 FinalSimulations

all: $(ALL)

clean:
	rm $(ALL) *.c *.h ; rm -rf bin

PrototypeBigSimulation3: PrototypeBigSimulation3.m cluster.m f.m logLikelihood.m ParkKimCichokiHybridSimData.m zhuEstimate.m cols.m FYandBICMultiresStrategy.m mitEstimateK_ntuNMF_Multires.m cophenet.m gaussianParameterEstimatesMLE.m nmfconsensus_taiwan.m row_sum.m corr.m laplace_pca.m nmforderconsensus.m StepFunctionColumns.m dendrogram.m linkage.m nmf_taiwan.m velicer.m iseuclidean.m inconsistent.m squareform.m RSSQ.m RRSSQ.m
	mcc -m -B sgl PrototypeBigSimulation3 cluster f logLikelihood ParkKimCichokiHybridSimData zhuEstimate cols FYandBICMultiresStrategy mitEstimateK_ntuNMF_Multires cophenet gaussianParameterEstimatesMLE nmfconsensus_taiwan row_sum corr laplace_pca nmforderconsensus StepFunctionColumns dendrogram linkage nmf_taiwan velicer iseuclidean inconsistent squareform RSSQ RRSSQ

FinalSimulations: FinalSimulations.m cluster.m f.m logLikelihood.m SimulateData_KD_N.m zhuEstimate.m cols.m FY_BIC_RRSSQ_KL.m cophenet.m gaussianParameterEstimatesMLE.m nmfconsensus.m row_sum.m corr.m laplace_pca.m nmforderconsensus.m dendrogram.m linkage.m velicer.m iseuclidean.m inconsistent.m squareform.m RSSQ.m gengabcvsvd.m gabr.m genbicvgps.m svdwrapper.m nmf_mit.m exprnd.m bic_pca.m repmat.m SimulateData_KD3.m SimulateData_KD4.m SimulateData_KD5.m SimulateData_KD6.m SimulateData_KD8.m SimulateData_KD10.m SimulateData_KD12.m SimulateData_KD14.m SimulateData_KD16.m
	mcc -m -B sgl FinalSimulations cluster f logLikelihood SimulateData_KD_N zhuEstimate cols FY_BIC_RRSSQ_KL cophenet gaussianParameterEstimatesMLE nmfconsensus row_sum corr laplace_pca nmforderconsensus dendrogram linkage velicer iseuclidean inconsistent squareform RSSQ gengabcvsvd gabr genbicvgps svdwrapper nmf_mit exprnd bic_pca repmat SimulateData_KD3 SimulateData_KD4 SimulateData_KD5 SimulateData_KD6 SimulateData_KD8 SimulateData_KD10 SimulateData_KD12 SimulateData_KD14 SimulateData_KD16

FinalSimulationsNoCCC: FinalSimulationsNoCCC.m cluster.m f.m logLikelihood.m SimulateData_KD_N.m zhuEstimate.m cols.m FY_BIC_RRSSQ_KL.m cophenet.m gaussianParameterEstimatesMLE.m nmfconsensus.m row_sum.m corr.m laplace_pca.m nmforderconsensus.m dendrogram.m linkage.m velicer.m iseuclidean.m inconsistent.m squareform.m RSSQ.m gengabcvsvd.m gabr.m genbicvgps.m svdwrapper.m nmf_mit.m exprnd.m bic_pca.m repmat.m SimulateData_KD3.m SimulateData_KD5.m SimulateData_KD8.m SimulateData_KD10.m SimulateData_KD12.m SimulateData_KD16.m
	mcc -m -B sgl FinalSimulationsNoCCC cluster f logLikelihood SimulateData_KD_N zhuEstimate cols FY_BIC_RRSSQ_KL cophenet gaussianParameterEstimatesMLE nmfconsensus row_sum corr laplace_pca nmforderconsensus dendrogram linkage velicer iseuclidean inconsistent squareform RSSQ gengabcvsvd gabr genbicvgps svdwrapper nmf_mit exprnd bic_pca repmat SimulateData_KD3 SimulateData_KD5 SimulateData_KD8 SimulateData_KD10 SimulateData_KD12 SimulateData_KD16

FinalSimulations_CCCOnly: FinalSimulations_CCCOnly.m cluster.m f.m logLikelihood.m SimulateData_KD_N.m zhuEstimate.m cols.m FY_BIC_RRSSQ_KL.m cophenet.m gaussianParameterEstimatesMLE.m nmfconsensus.m row_sum.m corr.m laplace_pca.m nmforderconsensus.m dendrogram.m linkage.m velicer.m iseuclidean.m inconsistent.m squareform.m RSSQ.m gengabcvsvd.m gabr.m genbicvgps.m svdwrapper.m nmf_mit.m exprnd.m bic_pca.m repmat.m SimulateData_KD3.m SimulateData_KD5.m SimulateData_KD8.m SimulateData_KD10.m SimulateData_KD12.m SimulateData_KD16.m
	mcc -m -B sgl FinalSimulations_CCCOnly cluster f logLikelihood SimulateData_KD_N zhuEstimate cols FY_BIC_RRSSQ_KL cophenet gaussianParameterEstimatesMLE nmfconsensus row_sum corr laplace_pca nmforderconsensus dendrogram linkage velicer iseuclidean inconsistent squareform RSSQ gengabcvsvd gabr genbicvgps svdwrapper nmf_mit exprnd bic_pca repmat SimulateData_KD3 SimulateData_KD5 SimulateData_KD8 SimulateData_KD10 SimulateData_KD12 SimulateData_KD16

BrunetOnlyCorrelatedData: BrunetOnlyCorrelatedData.m cluster.m f.m logLikelihood.m ParkKimCichokiHybridSimData.m zhuEstimate.m cols.m FYandBICMultiresStrategy.m mitEstimateK_ntuNMF_Multires2.m cophenet.m gaussianParameterEstimatesMLE.m nmfconsensus_taiwan.m row_sum.m corr.m laplace_pca.m nmforderconsensus.m StepFunctionColumns.m dendrogram.m linkage.m nmf_taiwan.m velicer.m iseuclidean.m inconsistent.m squareform.m RSSQ.m RRSSQ.m CorrelatedSyntheticData1.m GenerateCorrelationMatrix.m
	mcc -m -B sgl BrunetOnlyCorrelatedData cluster f logLikelihood ParkKimCichokiHybridSimData zhuEstimate cols FYandBICMultiresStrategy mitEstimateK_ntuNMF_Multires2 cophenet gaussianParameterEstimatesMLE nmfconsensus_taiwan row_sum corr laplace_pca nmforderconsensus StepFunctionColumns dendrogram linkage nmf_taiwan velicer iseuclidean inconsistent squareform RSSQ RRSSQ CorrelatedSyntheticData1 GenerateCorrelationMatrix

BrunetOnlyMultipleRuns2Transpose: BrunetOnlyMultipleRuns2Transpose.m cluster.m f.m logLikelihood.m ParkKimCichokiHybridSimData.m zhuEstimate.m cols.m FYandBICMultiresStrategy.m mitEstimateK_ntuNMF_Multires2.m cophenet.m gaussianParameterEstimatesMLE.m nmfconsensus_taiwan.m row_sum.m corr.m laplace_pca.m nmforderconsensus.m StepFunctionColumns.m dendrogram.m linkage.m nmf_taiwan.m velicer.m iseuclidean.m inconsistent.m squareform.m RSSQ.m RRSSQ.m
	mcc -m -B sgl BrunetOnlyMultipleRuns2Transpose cluster f logLikelihood ParkKimCichokiHybridSimData zhuEstimate cols FYandBICMultiresStrategy mitEstimateK_ntuNMF_Multires2 cophenet gaussianParameterEstimatesMLE nmfconsensus_taiwan row_sum corr laplace_pca nmforderconsensus StepFunctionColumns dendrogram linkage nmf_taiwan velicer iseuclidean inconsistent squareform RSSQ RRSSQ

BrunetOnlyMultipleRuns2: BrunetOnlyMultipleRuns2.m cluster.m f.m logLikelihood.m ParkKimCichokiHybridSimData.m zhuEstimate.m cols.m FYandBICMultiresStrategy.m mitEstimateK_ntuNMF_Multires2.m cophenet.m gaussianParameterEstimatesMLE.m nmfconsensus_taiwan.m row_sum.m corr.m laplace_pca.m nmforderconsensus.m StepFunctionColumns.m dendrogram.m linkage.m nmf_taiwan.m velicer.m iseuclidean.m inconsistent.m squareform.m RSSQ.m RRSSQ.m
	mcc -m -B sgl BrunetOnlyMultipleRuns2 cluster f logLikelihood ParkKimCichokiHybridSimData zhuEstimate cols FYandBICMultiresStrategy mitEstimateK_ntuNMF_Multires2 cophenet gaussianParameterEstimatesMLE nmfconsensus_taiwan row_sum corr laplace_pca nmforderconsensus StepFunctionColumns dendrogram linkage nmf_taiwan velicer iseuclidean inconsistent squareform RSSQ RRSSQ

BrunetOnlyMultipleRuns: BrunetOnlyMultipleRuns.m cluster.m f.m logLikelihood.m ParkKimCichokiHybridSimData.m zhuEstimate.m cols.m FYandBICMultiresStrategy.m mitEstimateK_ntuNMF_Multires2.m cophenet.m gaussianParameterEstimatesMLE.m nmfconsensus_taiwan.m row_sum.m corr.m laplace_pca.m nmforderconsensus.m StepFunctionColumns.m dendrogram.m linkage.m nmf_taiwan.m velicer.m iseuclidean.m inconsistent.m squareform.m RSSQ.m RRSSQ.m
	mcc -m -B sgl BrunetOnlyMultipleRuns cluster f logLikelihood ParkKimCichokiHybridSimData zhuEstimate cols FYandBICMultiresStrategy mitEstimateK_ntuNMF_Multires2 cophenet gaussianParameterEstimatesMLE nmfconsensus_taiwan row_sum corr laplace_pca nmforderconsensus StepFunctionColumns dendrogram linkage nmf_taiwan velicer iseuclidean inconsistent squareform RSSQ RRSSQ

BrunetOnly_PrototypeBigSimulation3: BrunetOnly_PrototypeBigSimulation3.m cluster.m f.m logLikelihood.m ParkKimCichokiHybridSimData.m zhuEstimate.m cols.m FYandBICMultiresStrategy.m mitEstimateK_ntuNMF_Multires2.m cophenet.m gaussianParameterEstimatesMLE.m nmfconsensus_taiwan.m row_sum.m corr.m laplace_pca.m nmforderconsensus.m StepFunctionColumns.m dendrogram.m linkage.m nmf_taiwan.m velicer.m iseuclidean.m inconsistent.m squareform.m RSSQ.m RRSSQ.m
	mcc -m -B sgl BrunetOnly_PrototypeBigSimulation3 cluster f logLikelihood ParkKimCichokiHybridSimData zhuEstimate cols FYandBICMultiresStrategy mitEstimateK_ntuNMF_Multires2 cophenet gaussianParameterEstimatesMLE nmfconsensus_taiwan row_sum corr laplace_pca nmforderconsensus StepFunctionColumns dendrogram linkage nmf_taiwan velicer iseuclidean inconsistent squareform RSSQ RRSSQ

PrototypeBigSimulation3_20Sim1: PrototypeBigSimulation3_20Sim1.m cluster.m f.m logLikelihood.m ParkKimCichokiHybridSimData.m zhuEstimate.m cols.m FYandBICMultiresStrategy.m mitEstimateK_ntuNMF_Multires.m cophenet.m gaussianParameterEstimatesMLE.m nmfconsensus_taiwan.m row_sum.m corr.m laplace_pca.m nmforderconsensus.m StepFunctionColumns.m dendrogram.m linkage.m nmf_taiwan.m velicer.m iseuclidean.m inconsistent.m squareform.m RSSQ.m RRSSQ.m
	mcc -m -B sgl PrototypeBigSimulation3_20Sim1 cluster f logLikelihood ParkKimCichokiHybridSimData zhuEstimate cols FYandBICMultiresStrategy mitEstimateK_ntuNMF_Multires cophenet gaussianParameterEstimatesMLE nmfconsensus_taiwan row_sum corr laplace_pca nmforderconsensus StepFunctionColumns dendrogram linkage nmf_taiwan velicer iseuclidean inconsistent squareform RSSQ RRSSQ

PrototypeBigSimulation3HalfNoise: PrototypeBigSimulation3HalfNoise.m cluster.m f.m logLikelihood.m ParkKimCichokiHybridSimData.m zhuEstimate.m cols.m FYandBICMultiresStrategy.m mitEstimateK_ntuNMF_Multires.m cophenet.m gaussianParameterEstimatesMLE.m nmfconsensus_taiwan.m row_sum.m corr.m laplace_pca.m nmforderconsensus.m StepFunctionColumns.m dendrogram.m linkage.m nmf_taiwan.m velicer.m iseuclidean.m inconsistent.m squareform.m RSSQ.m RRSSQ.m
	mcc -m -B sgl PrototypeBigSimulation3HalfNoise cluster f logLikelihood ParkKimCichokiHybridSimData zhuEstimate cols FYandBICMultiresStrategy mitEstimateK_ntuNMF_Multires cophenet gaussianParameterEstimatesMLE nmfconsensus_taiwan row_sum corr laplace_pca nmforderconsensus StepFunctionColumns dendrogram linkage nmf_taiwan velicer iseuclidean inconsistent squareform RSSQ RRSSQ

ProtoBigSimNoBrunet_25Rows: ProtoBigSimNoBrunet_25Rows.m cluster.m f.m logLikelihood.m ParkKimCichokiHybridSimData.m zhuEstimate.m cols.m FYandBICMultiresStrategy.m mitEstimateK_ntuNMF_Multires.m cophenet.m gaussianParameterEstimatesMLE.m nmfconsensus_taiwan.m row_sum.m corr.m laplace_pca.m nmforderconsensus.m StepFunctionColumns.m dendrogram.m linkage.m nmf_taiwan.m velicer.m iseuclidean.m inconsistent.m squareform.m RSSQ.m RRSSQ.m
	mcc -m -B sgl ProtoBigSimNoBrunet_25Rows cluster f logLikelihood ParkKimCichokiHybridSimData zhuEstimate cols FYandBICMultiresStrategy mitEstimateK_ntuNMF_Multires cophenet gaussianParameterEstimatesMLE nmfconsensus_taiwan row_sum corr laplace_pca nmforderconsensus StepFunctionColumns dendrogram linkage nmf_taiwan velicer iseuclidean inconsistent squareform RSSQ RRSSQ

ProtoBigSimNoBrunet: ProtoBigSimNoBrunet.m cluster.m f.m logLikelihood.m ParkKimCichokiHybridSimData.m zhuEstimate.m cols.m FYandBICMultiresStrategy.m mitEstimateK_ntuNMF_Multires.m cophenet.m gaussianParameterEstimatesMLE.m nmfconsensus_taiwan.m row_sum.m corr.m laplace_pca.m nmforderconsensus.m StepFunctionColumns.m dendrogram.m linkage.m nmf_taiwan.m velicer.m iseuclidean.m inconsistent.m squareform.m RSSQ.m RRSSQ.m
	mcc -m -B sgl ProtoBigSimNoBrunet cluster f logLikelihood ParkKimCichokiHybridSimData zhuEstimate cols FYandBICMultiresStrategy mitEstimateK_ntuNMF_Multires cophenet gaussianParameterEstimatesMLE nmfconsensus_taiwan row_sum corr laplace_pca nmforderconsensus StepFunctionColumns dendrogram linkage nmf_taiwan velicer iseuclidean inconsistent squareform RSSQ RRSSQ

SimWithCorrelatedDataNoBrunet1: SimWithCorrelatedDataNoBrunet1.m cluster.m f.m logLikelihood.m zhuEstimate.m cols.m FYandBICMultiresStrategy.m mitEstimateK_ntuNMF_Multires.m cophenet.m gaussianParameterEstimatesMLE.m nmfconsensus_taiwan.m row_sum.m corr.m laplace_pca.m nmforderconsensus.m StepFunctionColumns.m dendrogram.m linkage.m nmf_taiwan.m velicer.m iseuclidean.m inconsistent.m squareform.m RSSQ.m RRSSQ.m CorrelatedSyntheticData1.m GenerateCorrelationMatrix.m
	mcc -m -B sgl SimWithCorrelatedDataNoBrunet1 cluster f logLikelihood zhuEstimate cols FYandBICMultiresStrategy mitEstimateK_ntuNMF_Multires cophenet gaussianParameterEstimatesMLE nmfconsensus_taiwan row_sum corr laplace_pca nmforderconsensus StepFunctionColumns dendrogram linkage nmf_taiwan velicer iseuclidean inconsistent squareform RSSQ RRSSQ CorrelatedSyntheticData1 GenerateCorrelationMatrix

EstimateKOnNormalizedGolubData: EstimateKOnNormalizedGolubData.m f.m logLikelihood.m zhuEstimate.m FYandBICMultiresStrategy.m gaussianParameterEstimatesMLE.m laplace_pca.m nmf_taiwan.m velicer.m RSSQ.m RRSSQ.m mitEstimateK_ntuNMF_Multires.m cophenet.m gaussianParameterEstimatesMLE.m nmfconsensus_taiwan.m row_sum.m corr.m nmforderconsensus.m dendrogram.m linkage.m iseuclidean.m inconsistent.m squareform.m
	mcc -m -B sgl EstimateKOnNormalizedGolubData cluster f logLikelihood zhuEstimate FYandBICMultiresStrategy gaussianParameterEstimatesMLE row_sum laplace_pca nmf_taiwan velicer RSSQ RRSSQ mitEstimateK_ntuNMF_Multires cophenet gaussianParameterEstimatesMLE nmfconsensus_taiwan row_sum corr nmforderconsensus dendrogram linkage iseuclidean inconsistent squareform

EstimateKOnNormalizedGolubDataNoBrunet: EstimateKOnNormalizedGolubDataNoBrunet.m f.m logLikelihood.m zhuEstimate.m FYandBICMultiresStrategy.m gaussianParameterEstimatesMLE.m laplace_pca.m nmf_taiwan.m velicer.m RSSQ.m RRSSQ.m
	mcc -m -B sgl EstimateKOnNormalizedGolubDataNoBrunet cluster f logLikelihood zhuEstimate FYandBICMultiresStrategy gaussianParameterEstimatesMLE row_sum laplace_pca nmf_taiwan velicer RSSQ RRSSQ
